name: ESSD-benchmark-datasets
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - numpy
  - jupyter
  - matplotlib
  - xarray
  - zarr
  - dask
  - pip
  - pip:
          - climetlab
          - climetlab-eumetnet-postprocessing-benchmark

