name: ESSD-benchmark-datasets
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7
  - numpy
  - fsspec
  - requests
  - aiohttp
  - jupyter
  - matplotlib
  - xarray
  - zarr
  - dask
  - netCDF4
  - h5netcdf

